<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TproxyRelay.Tests" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.12" />
  </ItemGroup>

</Project>
